### ISSUE TITLE
[Bug]: can't access the official website.

### ISSUE THREAD

**Issue by hunnble** [wxmlfile/eslint-plugin-wxml#43]

**Comment by iChenLei** [comment]
@hunnble cloudflare gateway error ?  I can visit eslint-plugin-wxml.js.org via china unicom(中国联通) 4g.

**Comment by hunnble** [comment]
only happens in Chrome(v99).
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/14886515/158521773-17a21f80-c95e-405b-afb5-365ef57cb5ca.png">

can access in Safari too.

**Comment by iChenLei** [comment]
Ok, make sense. But can't reproduction on my macbook with chrome v99.
> chrome:://version
![2022-03-16 13 31 51](https://user-images.githubusercontent.com/14012511/158523060-b0838104-30ac-4870-9bd9-562d759dd66a.png)

> visit eslint-plugin-wxml.js.org
![2022-03-16 13 32 30](https://user-images.githubusercontent.com/14012511/158523132-f6da807f-f51c-47c5-8b5e-12d46693cc08.png)

**Comment by hunnble** [comment]
Thanks anyway.I'll use other browsers.
