### ISSUE TITLE
[Bug]: inline-wxs的时候为啥会有eslint报错

### ISSUE THREAD

**Issue by MelodyLLL** [wxmlfile/eslint-plugin-wxml#56]
**To reproduce:**
eslint的配置如官方 是
```
"overrides": [
    {
      "files": ["*.wxml"],
      "rules": {
        "wxml/report-wxml-syntax-error": "error",
        "wxml/wx-key":"error"
      },
      "plugins": ["wxml"],
      "processor": "wxml/wxml",
      "parser": "@wxml/parser"
    }
  ]
```

一个简单的示例是
```
<wxs module="handleSrc">
	module.exports = function(a){
           return null
	}
</wxs>
<view>
  <block>
    <view wx:for="{{[]}}"></view>
    <image src="#" />
  </block>
</view>
```

**Current behavior:**
项目是taro与微信混合的，自己在taro脚手架搭建的新项目上也尝试了一下，当wxs函数去掉a参数时，正常，
加上a参数时，重启eslint server立刻弹框报错，且key提示失效

**Expected behavior:**
不知道是不是因为eslint的原因，希望老师能给予解答，如果是bug，期望修复正常。

**Environment information:**
- `eslint` version:8.20.0
- `nodejs` version:14.19.1
- `eslint-plugin-wxml` version:0.7.3

- your IDE/editor: vscode

**Comment by MelodyLLL** [comment]
<img width="1051" alt="iShot2022-07-19 14 07 19" src="https://user-images.githubusercontent.com/91217601/179677766-0f15b8bd-9ada-409b-88ad-0606a095db70.png">
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/91217601/179677900-abde9724-a6d9-4824-96b1-b8eb61feb229.png">

**Comment by iChenLei** [comment]
@MelodyLLL 我个人建议是  `wxml` 和 `js / jsx / ts / tsx` 的配置 完全隔离开， 详见 https://eslint-plugin-wxml.js.org/user-guide/#usage
ESLint的弹窗错误说的比较清楚了，是 `react/sort-comp` 规则应用到 wxml 文件上了，然而`react/sort-comp`规则其实只能处理 `jsx` 文件

**Comment by MelodyLLL** [comment]
明白 感谢指点！
